### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by b1rdex** [editorconfig-checker/editorconfig-checker.javascript#316]
```
❯ npx --verbose editorconfig-checker -vvv -verbose -ignore-defaults -exclude "min\\.js$"
npm verb cli [
npm verb cli   '/opt/homebrew/Cellar/node/16.6.1/bin/node',
npm verb cli   '/opt/homebrew/lib/node_modules/npm/bin/npm-cli.js',
npm verb cli   'exec',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   '--',
npm verb cli   'editorconfig-checker',
npm verb cli   '-vvv',
npm verb cli   '-verbose',
npm verb cli   '-ignore-defaults',
npm verb cli   '-exclude',
npm verb cli   'min\\.js$'
npm verb cli ]
npm info using npm@7.20.3
npm info using node@v16.6.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/opt/homebrew/lib/node_modules/npm/npmrc Completed in 0ms
npm timing config:load:builtin Completed in 0ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 0ms
npm timing config:load:file:/redacted/.npmrc Completed in 0ms
npm timing config:load:project Completed in 0ms
npm timing config:load:file:/Users/anatoly/.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:/opt/homebrew/etc/npmrc Completed in 0ms
npm timing config:load:global Completed in 0ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 1ms
npm timing config:load:setEnvs Completed in 0ms
npm timing config:load Completed in 4ms
npm timing npm:load:configload Completed in 4ms
npm timing npm:load:setTitle Completed in 3ms
npm timing npm:load:setupLog Completed in 0ms
npm timing config:load:flatten Completed in 1ms
npm timing npm:load:cleanupLog Completed in 1ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load:projectScope Completed in 0ms
npm timing npm:load Completed in 12ms
ERROR: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/redacted/node_modules/tar/lib/warn-mixin.js:19:40)
    at Unpack.warn (/redacted/node_modules/tar/lib/unpack.js:189:18)
    at Unpack.<anonymous> (/redacted/node_modules/tar/lib/parse.js:81:14)
    at Unpack.emit (node:events:406:35)
    at Unpack.[emit] (/redacted/node_modules/tar/lib/parse.js:285:12)
    at Unpack.[maybeEnd] (/redacted/node_modules/tar/lib/parse.js:401:17)
    at Unpack.[consumeChunk] (/redacted/node_modules/tar/lib/parse.js:432:21)
    at Unpack.write (/redacted/node_modules/tar/lib/parse.js:364:25)
    at Unpack.end (/Users/anatoly/redacted/node_modules/tar/lib/parse.js:477:14)
    at Yallist.<anonymous> (/redacted/node_modules/minipass/index.js:396:18) {
  recoverable: false,
  file: '/redacted/node_modules/editorconfig-checker/dist/../ec.tar.gz',
  cwd: '/redacted/node_modules/editorconfig-checker',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
npm timing command:exec Completed in 1086ms
npm verb exit 0
npm timing npm Completed in 1170ms
npm info ok 

redacted on  develop [!] via  v16.6.1 
❯ file /redacted/node_modules/editorconfig-checker/dist/../ec.tar.gz                                                  
/redacted/node_modules/editorconfig-checker/dist/../ec.tar.gz: ASCII text, with no line terminators

redacted on  develop [!] via  v16.6.1 
❯ cat /redacted/node_modules/editorconfig-checker/dist/../ec.tar.gz               
Not Found%                                                                                                                                                                     

```

**Comment by chalkygames123** [comment]
Seems to be fixed in editorconfig-checker v2.5.0 🎉

**Comment by mstruebing** [comment]
Do we need another release for editorconfig-checker.javascript or is everything working fine?

**Comment by mstruebing** [comment]
Thanks for clarifying this.

**Comment by LitoMore** [comment]
> Do we need another release for editorconfig-checker.javascript or is everything working fine? (@mstruebing)

We should. I still encounter the failing error `Error: TAR_BAD_ARCHIVE: Unrecognized archive format`. And everything went well after I applied the latest code.

Or we can release a beta version with a [disg-tag](https://docs.npmjs.com/adding-dist-tags-to-packages). The version should be `5.0.0-beta.0`.
