### ISSUE TITLE
Not able to run editorconfig-checker on Win10

### ISSUE THREAD

**Issue by jenssimon** [editorconfig-checker/editorconfig-checker.javascript#53]
On Windows (VM running Windows 10, 10.0.17134) I'm not able to run `editorconfig-checker`.

I'm using yarn and following `package.json`:

```json
  "scripts": {
    "editorconfig-checker": "editorconfig-checker"
  }
```

Result:

```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\IEUser\dev\dpv\node_modules\editorconfig-checker\dist/../bin/ec-windows-amd64 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
```

After renaming `node_modules/editorconfig-checker/bin/ec-windows-amd64` to `node_modules/editorconfig-checker/bin/ec-windows-amd64.exe` everything works fine.

The problem descibed in https://github.com/editorconfig-checker/editorconfig-checker/issues/46

**Comment by mstruebing** [comment]
Could you try if this issue is fixed with version 2.0.2?

**Comment by jenssimon** [comment]
Same error with 2.0.2 but I can't find a `node_modules/editorconfig_checker/bin` folder
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\IEUser\dev\dpv\node_modules\editorconfig-checker\dist/../bin/ec-windows-amd64 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
error Command failed with exit code 1.
```

**Comment by mstruebing** [comment]
Sorry, this was definitely my fault, I've not paid enough attention to the windows specialities. Working now with 2.0.4?

**Comment by jenssimon** [comment]
Works using 2.0.5. Thank you!

No worries. Nobody has fun with cross platform topics.
